#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: make
# autospec version: v21
# autospec commit: 94c6be0
#
%define keepstatic 1
Name     : openjdk
Version  : 21.0.5.11.1
Release  : 100
URL      : https://github.com/corretto/corretto-21/archive/refs/tags/21.0.5.11.1.tar.gz
Source0  : https://github.com/corretto/corretto-21/archive/refs/tags/21.0.5.11.1.tar.gz
Source1  : https://corretto.aws/downloads/resources/21.0.5.11.1/amazon-corretto-21.0.5.11.1-linux-x64.tar.gz
Summary  : APPLICATION_SUMMARY
Group    : Development/Tools
License  : GPL-2.0 MIT libpng-2.0
Requires: openjdk-bin = %{version}-%{release}
Requires: openjdk-lib = %{version}-%{release}
Requires: openjdk-license = %{version}-%{release}
BuildRequires : alsa-lib-dev
BuildRequires : ca-certs
BuildRequires : cups-dev
BuildRequires : freetype-dev
BuildRequires : gcc11-dev
BuildRequires : libX11-dev
BuildRequires : libXext-dev
BuildRequires : libXi-dev
BuildRequires : libXrender-dev
BuildRequires : libXt-dev
BuildRequires : libXtst-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : openjdk
BuildRequires : openjdk-dev
BuildRequires : pandoc
BuildRequires : pkgconfig(fontconfig)
BuildRequires : zip
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: scaling.patch

%description
APPLICATION_DESCRIPTION

%package bin
Summary: bin components for the openjdk package.
Group: Binaries
Requires: openjdk-license = %{version}-%{release}

%description bin
bin components for the openjdk package.


%package dev
Summary: dev components for the openjdk package.
Group: Development
Requires: openjdk-lib = %{version}-%{release}
Requires: openjdk-bin = %{version}-%{release}
Provides: openjdk-devel = %{version}-%{release}
Requires: openjdk = %{version}-%{release}

%description dev
dev components for the openjdk package.


%package lib
Summary: lib components for the openjdk package.
Group: Libraries
Requires: openjdk-license = %{version}-%{release}

%description lib
lib components for the openjdk package.


%package license
Summary: license components for the openjdk package.
Group: Default

%description license
license components for the openjdk package.


%prep
%setup -q -n corretto-21-21.0.5.11.1
cd %{_builddir}
tar xf %{_sourcedir}/amazon-corretto-21.0.5.11.1-linux-x64.tar.gz
cd %{_builddir}/corretto-21-21.0.5.11.1
mkdir -p ./prebuilt
cp -r %{_builddir}/amazon-corretto-21.0.5.11.1-linux-x64/* %{_builddir}/corretto-21-21.0.5.11.1/./prebuilt
%patch -P 1 -p1

%build
## build_prepend content
pushd ..
cp -a corretto-* buildavx2
cd buildavx2
CLR_TRUST_STORE=%{_builddir}/trust-store clrtrust generate
export CXXFLAGS="$CXXFLAGS -std=gnu++98 -Wno-error -fno-delete-null-pointer-checks -fno-guess-branch-probability -fno-lto"
export CXXFLAGS_JDK="$CXXFLAGS"
export CC=/usr/bin/gcc
export CXX=/usr//bin/g++
export SYSDEFS="$CXXFLAGS"
# when updating use
# --with-boot-jdk=/builddir/build/BUILD/corretto-21-21.0.5.11.1/prebuilt/ \
# then switch to
# --with-boot-jdk=/usr/lib/jvm/openjdk-21.0.5-internal/ \
bash configure \
--with-boot-jdk=/usr/lib/jvm/openjdk-21.0.5-internal/ \
--x-includes=/usr/include/ \
--x-libraries=/usr/lib64 \
--with-extra-cflags="-O3 -g1 -fno-lto" \
--with-extra-cxxflags="$CXXFLAGS -g1 -fno-lto" \
--with-zlib=system \
--enable-unlimited-crypto \
--with-cacerts-file=%{_builddir}/trust-store/compat/ca-roots.keystore \
--prefix=%{buildroot}/usr/lib  \
--with-extra-cxxflags="-O3 -march=haswell -fno-semantic-interposition  " \
--with-extra-cflags="-O3 -march=haswell -fno-semantic-interposition " \
--with-jvm-features="zgc shenandoahgc" \
--with-freetype=system --with-libjpeg=system --with-libpng=system --with-zlib=system --with-vendor-name="Clear Linux"--with-debug-level=release \
--prefix=/usr --disable-warnings-as-errors

make
# bad hack because there is something race like on the first run of make images
make images || :
make images

popd

bash configure \
--with-boot-jdk=/usr/lib/jvm/openjdk-21.0.5-internal/ \
--x-includes=/usr/include/ \
--x-libraries=/usr/lib64 \
--with-extra-cflags="-O3 -g1 -fno-lto" \
--with-extra-cxxflags="$CXXFLAGS -g1 -fno-lto" \
--with-zlib=system \
--enable-unlimited-crypto \
--with-cacerts-file=%{_builddir}/trust-store/compat/ca-roots.keystore \
--prefix=%{buildroot}/usr/lib  \
--with-extra-cxxflags="-O3 -march=westmere -fno-semantic-interposition  " \
--with-extra-cflags="-O3 -march=westmere -fno-semantic-interposition " \
--with-jvm-features="zgc shenandoahgc" \
--with-freetype=system --with-libjpeg=system --with-libpng=system --with-zlib=system --with-vendor-name="Clear Linux" --with-debug-level=release \
--prefix=/usr --disable-warnings-as-errors

make
make images
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1738289532
unset LD_AS_NEEDED
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
make  all WARNINGS_ARE_ERRORS=


%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1738289532
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/openjdk
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/java.base/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/java.compiler/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/java.datatransfer/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/java.desktop/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/java.instrument/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/java.logging/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/java.management.rmi/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/java.management/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/java.naming/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/java.net.http/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/java.prefs/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/java.rmi/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/java.scripting/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/java.se/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/java.security.jgss/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/java.security.sasl/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/java.smartcardio/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/java.sql.rowset/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/java.sql/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/java.transaction.xa/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/java.xml.crypto/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/java.xml/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/jdk.accessibility/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/jdk.attach/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/jdk.charsets/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/jdk.compiler/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/jdk.crypto.cryptoki/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/jdk.crypto.ec/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/jdk.dynalink/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/jdk.editpad/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/jdk.hotspot.agent/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/jdk.httpserver/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/jdk.incubator.vector/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/jdk.internal.ed/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/jdk.internal.jvmstat/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/jdk.internal.le/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/jdk.internal.opt/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/jdk.internal.vm.ci/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/jdk.internal.vm.compiler.management/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/jdk.internal.vm.compiler/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/jdk.jartool/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/jdk.javadoc/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/jdk.jcmd/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/jdk.jconsole/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/jdk.jdeps/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/jdk.jdi/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/jdk.jdwp.agent/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/jdk.jfr/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/jdk.jlink/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/jdk.jpackage/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/jdk.jshell/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/jdk.jsobject/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/jdk.jstatd/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/jdk.localedata/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/jdk.management.agent/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/jdk.management.jfr/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/jdk.management/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/jdk.naming.dns/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/jdk.naming.rmi/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/jdk.net/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/jdk.nio.mapmode/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/jdk.random/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/jdk.sctp/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/jdk.security.auth/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/jdk.security.jgss/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/jdk.unsupported.desktop/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/jdk.unsupported/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/jdk.xml.dom/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/amazon-corretto-%{version}-linux-x64/legal/jdk.zipfs/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/corretto-21-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f || :
cp %{_builddir}/corretto-21-%{version}/src/java.desktop/share/native/libsplashscreen/giflib/COPYING %{buildroot}/usr/share/package-licenses/openjdk/f9c9a2d3495a0766b4cf20d4b90cfe714dab3dc1 || :
cp %{_builddir}/corretto-21-%{version}/src/java.desktop/share/native/libsplashscreen/libpng/LICENSE %{buildroot}/usr/share/package-licenses/openjdk/570f5344ea5facacb5e0bbb3fe4e0674189a5f0e || :
export GOAMD64=v2
GOAMD64=v2
%make_install INSTALL_PREFIX=%{buildroot} help || :
## install_append content
pushd ../buildavx2/
%make_install_v3 INSTALL_PREFIX=%{buildroot}-v3 help || :
popd

mkdir -p %{buildroot}/usr/lib
mkdir -p %{buildroot}/usr/lib64
mkdir -p %{buildroot}-v3/usr/lib
mkdir -p %{buildroot}-v3/usr/lib64

cp %{buildroot}/jvm/*/lib/libjli.so %{buildroot}/usr/lib64
cp %{buildroot}-v3/jvm/*/lib/libjli.so %{buildroot}-v3/usr/lib64

mv %{buildroot}/jvm/ %{buildroot}/usr/lib/
mv %{buildroot}-v3/jvm/ %{buildroot}-v3/usr/lib/

echo "-server KNOWN" > jvm.cfg
echo "-client IGNORE" >> jvm.cfg
mv jvm.cfg %{buildroot}/usr/lib/jvm/*/lib/

rm -f {buildroot}/usr/lib/jvm/openjdk-*-internal/lib/tzdb.dat

cp build/linux-x86_64-server-release/jdk/lib/tzdb.dat %{buildroot}/usr/lib/jvm/*/lib/
find %{buildroot}/usr/bin -type l -exec sh -c '
target=$(readlink "{}");
prefix="%{buildroot}";
stripped_target="${target#$prefix}";
ln -sf "/usr/lib${stripped_target}" "{}";
' \;

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
## install_append end

%files
%defattr(-,root,root,-)
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/jar
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/jar.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/jarsigner
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/jarsigner.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/java
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/java.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/javac
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/javac.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/javadoc
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/javadoc.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/javap
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/javap.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/jcmd
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/jcmd.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/jconsole
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/jconsole.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/jdb
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/jdb.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/jdeprscan
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/jdeprscan.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/jdeps
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/jdeps.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/jfr
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/jfr.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/jhsdb
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/jhsdb.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/jimage
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/jimage.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/jinfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/jinfo.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/jlink
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/jlink.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/jmap
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/jmap.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/jmod
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/jmod.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/jpackage
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/jpackage.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/jps
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/jps.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/jrunscript
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/jrunscript.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/jshell
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/jshell.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/jstack
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/jstack.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/jstat
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/jstat.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/jstatd
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/jstatd.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/jwebserver
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/jwebserver.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/keytool
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/keytool.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/rmiregistry
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/rmiregistry.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/serialver
/V3/usr/lib/jvm/openjdk-21.0.5-internal/bin/serialver.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/jexec
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/jexec.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/jspawnhelper
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/jspawnhelper.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libattach.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libawt.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libawt_headless.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libawt_xawt.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libdt_socket.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libextnet.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libfontmanager.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libinstrument.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libj2gss.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libj2pcsc.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libj2pkcs11.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libjaas.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libjava.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libjavajpeg.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libjawt.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libjdwp.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libjimage.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libjli.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libjsig.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libjsound.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libjsvml.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/liblcms.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/lible.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libmanagement.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libmanagement_agent.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libmanagement_ext.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libmlib_image.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libnet.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libnio.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libprefs.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/librmi.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libsaproc.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libsctp.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libsplashscreen.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libsyslookup.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libverify.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libzip.debuginfo
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/server/libjvm.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/bin/jar
/usr/lib/jvm/openjdk-21.0.5-internal/bin/jar.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/bin/jarsigner
/usr/lib/jvm/openjdk-21.0.5-internal/bin/jarsigner.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/bin/java
/usr/lib/jvm/openjdk-21.0.5-internal/bin/java.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/bin/javac
/usr/lib/jvm/openjdk-21.0.5-internal/bin/javac.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/bin/javadoc
/usr/lib/jvm/openjdk-21.0.5-internal/bin/javadoc.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/bin/javap
/usr/lib/jvm/openjdk-21.0.5-internal/bin/javap.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/bin/jcmd
/usr/lib/jvm/openjdk-21.0.5-internal/bin/jcmd.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/bin/jconsole
/usr/lib/jvm/openjdk-21.0.5-internal/bin/jconsole.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/bin/jdb
/usr/lib/jvm/openjdk-21.0.5-internal/bin/jdb.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/bin/jdeprscan
/usr/lib/jvm/openjdk-21.0.5-internal/bin/jdeprscan.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/bin/jdeps
/usr/lib/jvm/openjdk-21.0.5-internal/bin/jdeps.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/bin/jfr
/usr/lib/jvm/openjdk-21.0.5-internal/bin/jfr.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/bin/jhsdb
/usr/lib/jvm/openjdk-21.0.5-internal/bin/jhsdb.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/bin/jimage
/usr/lib/jvm/openjdk-21.0.5-internal/bin/jimage.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/bin/jinfo
/usr/lib/jvm/openjdk-21.0.5-internal/bin/jinfo.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/bin/jlink
/usr/lib/jvm/openjdk-21.0.5-internal/bin/jlink.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/bin/jmap
/usr/lib/jvm/openjdk-21.0.5-internal/bin/jmap.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/bin/jmod
/usr/lib/jvm/openjdk-21.0.5-internal/bin/jmod.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/bin/jpackage
/usr/lib/jvm/openjdk-21.0.5-internal/bin/jpackage.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/bin/jps
/usr/lib/jvm/openjdk-21.0.5-internal/bin/jps.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/bin/jrunscript
/usr/lib/jvm/openjdk-21.0.5-internal/bin/jrunscript.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/bin/jshell
/usr/lib/jvm/openjdk-21.0.5-internal/bin/jshell.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/bin/jstack
/usr/lib/jvm/openjdk-21.0.5-internal/bin/jstack.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/bin/jstat
/usr/lib/jvm/openjdk-21.0.5-internal/bin/jstat.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/bin/jstatd
/usr/lib/jvm/openjdk-21.0.5-internal/bin/jstatd.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/bin/jwebserver
/usr/lib/jvm/openjdk-21.0.5-internal/bin/jwebserver.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/bin/keytool
/usr/lib/jvm/openjdk-21.0.5-internal/bin/keytool.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/bin/rmiregistry
/usr/lib/jvm/openjdk-21.0.5-internal/bin/rmiregistry.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/bin/serialver
/usr/lib/jvm/openjdk-21.0.5-internal/bin/serialver.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/conf/jaxp.properties
/usr/lib/jvm/openjdk-21.0.5-internal/conf/logging.properties
/usr/lib/jvm/openjdk-21.0.5-internal/conf/management/jmxremote.access
/usr/lib/jvm/openjdk-21.0.5-internal/conf/management/jmxremote.password.template
/usr/lib/jvm/openjdk-21.0.5-internal/conf/management/management.properties
/usr/lib/jvm/openjdk-21.0.5-internal/conf/net.properties
/usr/lib/jvm/openjdk-21.0.5-internal/conf/sdp/sdp.conf.template
/usr/lib/jvm/openjdk-21.0.5-internal/conf/security/java.policy
/usr/lib/jvm/openjdk-21.0.5-internal/conf/security/java.security
/usr/lib/jvm/openjdk-21.0.5-internal/conf/security/policy/README.txt
/usr/lib/jvm/openjdk-21.0.5-internal/conf/security/policy/limited/default_US_export.policy
/usr/lib/jvm/openjdk-21.0.5-internal/conf/security/policy/limited/default_local.policy
/usr/lib/jvm/openjdk-21.0.5-internal/conf/security/policy/limited/exempt_local.policy
/usr/lib/jvm/openjdk-21.0.5-internal/conf/security/policy/unlimited/default_US_export.policy
/usr/lib/jvm/openjdk-21.0.5-internal/conf/security/policy/unlimited/default_local.policy
/usr/lib/jvm/openjdk-21.0.5-internal/conf/sound.properties
/usr/lib/jvm/openjdk-21.0.5-internal/demo/README
/usr/lib/jvm/openjdk-21.0.5-internal/demo/jfc/CodePointIM/CodePointIM.jar
/usr/lib/jvm/openjdk-21.0.5-internal/demo/jfc/CodePointIM/README.html
/usr/lib/jvm/openjdk-21.0.5-internal/demo/jfc/CodePointIM/README_ja.html
/usr/lib/jvm/openjdk-21.0.5-internal/demo/jfc/CodePointIM/README_zh_CN.html
/usr/lib/jvm/openjdk-21.0.5-internal/demo/jfc/CodePointIM/src.zip
/usr/lib/jvm/openjdk-21.0.5-internal/demo/jfc/FileChooserDemo/FileChooserDemo.jar
/usr/lib/jvm/openjdk-21.0.5-internal/demo/jfc/FileChooserDemo/README.txt
/usr/lib/jvm/openjdk-21.0.5-internal/demo/jfc/FileChooserDemo/src.zip
/usr/lib/jvm/openjdk-21.0.5-internal/demo/jfc/Font2DTest/Font2DTest.jar
/usr/lib/jvm/openjdk-21.0.5-internal/demo/jfc/Font2DTest/README.txt
/usr/lib/jvm/openjdk-21.0.5-internal/demo/jfc/Font2DTest/src.zip
/usr/lib/jvm/openjdk-21.0.5-internal/demo/jfc/J2Ddemo/J2Ddemo.jar
/usr/lib/jvm/openjdk-21.0.5-internal/demo/jfc/J2Ddemo/README.txt
/usr/lib/jvm/openjdk-21.0.5-internal/demo/jfc/J2Ddemo/src.zip
/usr/lib/jvm/openjdk-21.0.5-internal/demo/jfc/Metalworks/Metalworks.jar
/usr/lib/jvm/openjdk-21.0.5-internal/demo/jfc/Metalworks/README.txt
/usr/lib/jvm/openjdk-21.0.5-internal/demo/jfc/Metalworks/src.zip
/usr/lib/jvm/openjdk-21.0.5-internal/demo/jfc/Notepad/Notepad.jar
/usr/lib/jvm/openjdk-21.0.5-internal/demo/jfc/Notepad/README.txt
/usr/lib/jvm/openjdk-21.0.5-internal/demo/jfc/Notepad/src.zip
/usr/lib/jvm/openjdk-21.0.5-internal/demo/jfc/SampleTree/README.txt
/usr/lib/jvm/openjdk-21.0.5-internal/demo/jfc/SampleTree/SampleTree.jar
/usr/lib/jvm/openjdk-21.0.5-internal/demo/jfc/SampleTree/src.zip
/usr/lib/jvm/openjdk-21.0.5-internal/demo/jfc/Stylepad/README.txt
/usr/lib/jvm/openjdk-21.0.5-internal/demo/jfc/Stylepad/Stylepad.jar
/usr/lib/jvm/openjdk-21.0.5-internal/demo/jfc/Stylepad/src.zip
/usr/lib/jvm/openjdk-21.0.5-internal/demo/jfc/SwingSet2/README.txt
/usr/lib/jvm/openjdk-21.0.5-internal/demo/jfc/SwingSet2/SwingSet2.jar
/usr/lib/jvm/openjdk-21.0.5-internal/demo/jfc/SwingSet2/src.zip
/usr/lib/jvm/openjdk-21.0.5-internal/demo/jfc/TableExample/README.txt
/usr/lib/jvm/openjdk-21.0.5-internal/demo/jfc/TableExample/TableExample.jar
/usr/lib/jvm/openjdk-21.0.5-internal/demo/jfc/TableExample/src.zip
/usr/lib/jvm/openjdk-21.0.5-internal/demo/jfc/TransparentRuler/README.txt
/usr/lib/jvm/openjdk-21.0.5-internal/demo/jfc/TransparentRuler/TransparentRuler.jar
/usr/lib/jvm/openjdk-21.0.5-internal/demo/jfc/TransparentRuler/src.zip
/usr/lib/jvm/openjdk-21.0.5-internal/demo/nbproject/README.txt
/usr/lib/jvm/openjdk-21.0.5-internal/demo/nbproject/jfc/FileChooserDemo/build.properties
/usr/lib/jvm/openjdk-21.0.5-internal/demo/nbproject/jfc/FileChooserDemo/build.xml
/usr/lib/jvm/openjdk-21.0.5-internal/demo/nbproject/jfc/FileChooserDemo/nbproject/file-targets.xml
/usr/lib/jvm/openjdk-21.0.5-internal/demo/nbproject/jfc/FileChooserDemo/nbproject/jdk.xml
/usr/lib/jvm/openjdk-21.0.5-internal/demo/nbproject/jfc/FileChooserDemo/nbproject/netbeans-targets.xml
/usr/lib/jvm/openjdk-21.0.5-internal/demo/nbproject/jfc/FileChooserDemo/nbproject/project.xml
/usr/lib/jvm/openjdk-21.0.5-internal/demo/nbproject/jfc/Font2DTest/build.properties
/usr/lib/jvm/openjdk-21.0.5-internal/demo/nbproject/jfc/Font2DTest/build.xml
/usr/lib/jvm/openjdk-21.0.5-internal/demo/nbproject/jfc/Font2DTest/nbproject/file-targets.xml
/usr/lib/jvm/openjdk-21.0.5-internal/demo/nbproject/jfc/Font2DTest/nbproject/jdk.xml
/usr/lib/jvm/openjdk-21.0.5-internal/demo/nbproject/jfc/Font2DTest/nbproject/netbeans-targets.xml
/usr/lib/jvm/openjdk-21.0.5-internal/demo/nbproject/jfc/Font2DTest/nbproject/project.xml
/usr/lib/jvm/openjdk-21.0.5-internal/demo/nbproject/jfc/Metalworks/build.properties
/usr/lib/jvm/openjdk-21.0.5-internal/demo/nbproject/jfc/Metalworks/build.xml
/usr/lib/jvm/openjdk-21.0.5-internal/demo/nbproject/jfc/Metalworks/nbproject/file-targets.xml
/usr/lib/jvm/openjdk-21.0.5-internal/demo/nbproject/jfc/Metalworks/nbproject/jdk.xml
/usr/lib/jvm/openjdk-21.0.5-internal/demo/nbproject/jfc/Metalworks/nbproject/netbeans-targets.xml
/usr/lib/jvm/openjdk-21.0.5-internal/demo/nbproject/jfc/Metalworks/nbproject/project.xml
/usr/lib/jvm/openjdk-21.0.5-internal/demo/nbproject/jfc/Notepad/build.properties
/usr/lib/jvm/openjdk-21.0.5-internal/demo/nbproject/jfc/Notepad/build.xml
/usr/lib/jvm/openjdk-21.0.5-internal/demo/nbproject/jfc/Notepad/nbproject/file-targets.xml
/usr/lib/jvm/openjdk-21.0.5-internal/demo/nbproject/jfc/Notepad/nbproject/jdk.xml
/usr/lib/jvm/openjdk-21.0.5-internal/demo/nbproject/jfc/Notepad/nbproject/netbeans-targets.xml
/usr/lib/jvm/openjdk-21.0.5-internal/demo/nbproject/jfc/Notepad/nbproject/project.xml
/usr/lib/jvm/openjdk-21.0.5-internal/demo/nbproject/jfc/SampleTree/build.properties
/usr/lib/jvm/openjdk-21.0.5-internal/demo/nbproject/jfc/SampleTree/build.xml
/usr/lib/jvm/openjdk-21.0.5-internal/demo/nbproject/jfc/SampleTree/nbproject/file-targets.xml
/usr/lib/jvm/openjdk-21.0.5-internal/demo/nbproject/jfc/SampleTree/nbproject/jdk.xml
/usr/lib/jvm/openjdk-21.0.5-internal/demo/nbproject/jfc/SampleTree/nbproject/netbeans-targets.xml
/usr/lib/jvm/openjdk-21.0.5-internal/demo/nbproject/jfc/SampleTree/nbproject/project.xml
/usr/lib/jvm/openjdk-21.0.5-internal/demo/nbproject/jfc/TableExample/build.properties
/usr/lib/jvm/openjdk-21.0.5-internal/demo/nbproject/jfc/TableExample/build.xml
/usr/lib/jvm/openjdk-21.0.5-internal/demo/nbproject/jfc/TableExample/nbproject/file-targets.xml
/usr/lib/jvm/openjdk-21.0.5-internal/demo/nbproject/jfc/TableExample/nbproject/jdk.xml
/usr/lib/jvm/openjdk-21.0.5-internal/demo/nbproject/jfc/TableExample/nbproject/netbeans-targets.xml
/usr/lib/jvm/openjdk-21.0.5-internal/demo/nbproject/jfc/TableExample/nbproject/project.xml
/usr/lib/jvm/openjdk-21.0.5-internal/demo/nbproject/jfc/TransparentRuler/build.properties
/usr/lib/jvm/openjdk-21.0.5-internal/demo/nbproject/jfc/TransparentRuler/build.xml
/usr/lib/jvm/openjdk-21.0.5-internal/demo/nbproject/jfc/TransparentRuler/nbproject/file-targets.xml
/usr/lib/jvm/openjdk-21.0.5-internal/demo/nbproject/jfc/TransparentRuler/nbproject/jdk.xml
/usr/lib/jvm/openjdk-21.0.5-internal/demo/nbproject/jfc/TransparentRuler/nbproject/netbeans-targets.xml
/usr/lib/jvm/openjdk-21.0.5-internal/demo/nbproject/jfc/TransparentRuler/nbproject/project.xml
/usr/lib/jvm/openjdk-21.0.5-internal/demo/nbproject/project.xml
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/java.base.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/java.compiler.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/java.datatransfer.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/java.desktop.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/java.instrument.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/java.logging.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/java.management.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/java.management.rmi.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/java.naming.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/java.net.http.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/java.prefs.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/java.rmi.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/java.scripting.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/java.se.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/java.security.jgss.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/java.security.sasl.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/java.smartcardio.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/java.sql.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/java.sql.rowset.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/java.transaction.xa.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/java.xml.crypto.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/java.xml.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/jdk.accessibility.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/jdk.attach.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/jdk.charsets.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/jdk.compiler.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/jdk.crypto.cryptoki.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/jdk.crypto.ec.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/jdk.dynalink.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/jdk.editpad.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/jdk.hotspot.agent.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/jdk.httpserver.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/jdk.incubator.vector.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/jdk.internal.ed.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/jdk.internal.jvmstat.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/jdk.internal.le.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/jdk.internal.opt.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/jdk.internal.vm.ci.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/jdk.internal.vm.compiler.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/jdk.internal.vm.compiler.management.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/jdk.jartool.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/jdk.javadoc.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/jdk.jcmd.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/jdk.jconsole.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/jdk.jdeps.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/jdk.jdi.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/jdk.jdwp.agent.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/jdk.jfr.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/jdk.jlink.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/jdk.jpackage.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/jdk.jshell.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/jdk.jsobject.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/jdk.jstatd.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/jdk.localedata.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/jdk.management.agent.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/jdk.management.jfr.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/jdk.management.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/jdk.naming.dns.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/jdk.naming.rmi.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/jdk.net.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/jdk.nio.mapmode.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/jdk.random.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/jdk.sctp.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/jdk.security.auth.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/jdk.security.jgss.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/jdk.unsupported.desktop.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/jdk.unsupported.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/jdk.xml.dom.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/jmods/jdk.zipfs.jmod
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.base/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.base/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.base/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.base/aes.md
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.base/asm.md
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.base/c-libutl.md
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.base/cldr.md
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.base/icu.md
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.base/public_suffix.md
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.base/siphash.md
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.base/unicode.md
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.compiler/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.compiler/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.compiler/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.datatransfer/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.datatransfer/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.datatransfer/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.desktop/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.desktop/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.desktop/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.desktop/colorimaging.md
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.desktop/giflib.md
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.desktop/harfbuzz.md
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.desktop/lcms.md
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.desktop/mesa3d.md
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.desktop/pipewire.md
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.desktop/xwd.md
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.instrument/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.instrument/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.instrument/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.logging/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.logging/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.logging/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.management.rmi/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.management.rmi/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.management.rmi/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.management/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.management/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.management/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.naming/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.naming/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.naming/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.net.http/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.net.http/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.net.http/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.prefs/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.prefs/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.prefs/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.rmi/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.rmi/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.rmi/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.scripting/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.scripting/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.scripting/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.se/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.se/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.se/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.security.jgss/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.security.jgss/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.security.jgss/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.security.sasl/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.security.sasl/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.security.sasl/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.smartcardio/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.smartcardio/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.smartcardio/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.smartcardio/pcsclite.md
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.sql.rowset/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.sql.rowset/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.sql.rowset/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.sql/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.sql/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.sql/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.transaction.xa/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.transaction.xa/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.transaction.xa/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.xml.crypto/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.xml.crypto/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.xml.crypto/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.xml.crypto/santuario.md
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.xml/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.xml/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.xml/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.xml/bcel.md
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.xml/dom.md
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.xml/jcup.md
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.xml/xalan.md
/usr/lib/jvm/openjdk-21.0.5-internal/legal/java.xml/xerces.md
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.accessibility/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.accessibility/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.accessibility/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.attach/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.attach/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.attach/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.charsets/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.charsets/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.charsets/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.compiler/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.compiler/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.compiler/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.crypto.cryptoki/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.crypto.cryptoki/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.crypto.cryptoki/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.crypto.cryptoki/pkcs11cryptotoken.md
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.crypto.cryptoki/pkcs11wrapper.md
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.crypto.ec/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.crypto.ec/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.crypto.ec/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.dynalink/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.dynalink/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.dynalink/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.dynalink/dynalink.md
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.editpad/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.editpad/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.editpad/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.hotspot.agent/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.hotspot.agent/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.hotspot.agent/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.httpserver/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.httpserver/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.httpserver/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.incubator.vector/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.incubator.vector/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.incubator.vector/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.internal.ed/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.internal.ed/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.internal.ed/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.internal.jvmstat/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.internal.jvmstat/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.internal.jvmstat/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.internal.le/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.internal.le/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.internal.le/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.internal.le/jline.md
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.internal.opt/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.internal.opt/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.internal.opt/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.internal.opt/jopt-simple.md
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.internal.vm.ci/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.internal.vm.ci/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.internal.vm.ci/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.internal.vm.compiler.management/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.internal.vm.compiler.management/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.internal.vm.compiler.management/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.internal.vm.compiler/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.internal.vm.compiler/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.internal.vm.compiler/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.jartool/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.jartool/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.jartool/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.javadoc/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.javadoc/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.javadoc/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.javadoc/jquery.md
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.javadoc/jqueryUI.md
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.jcmd/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.jcmd/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.jcmd/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.jconsole/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.jconsole/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.jconsole/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.jdeps/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.jdeps/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.jdeps/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.jdi/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.jdi/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.jdi/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.jdwp.agent/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.jdwp.agent/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.jdwp.agent/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.jfr/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.jfr/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.jfr/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.jlink/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.jlink/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.jlink/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.jpackage/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.jpackage/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.jpackage/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.jshell/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.jshell/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.jshell/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.jsobject/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.jsobject/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.jsobject/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.jstatd/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.jstatd/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.jstatd/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.localedata/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.localedata/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.localedata/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.localedata/cldr.md
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.localedata/thaidict.md
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.management.agent/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.management.agent/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.management.agent/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.management.jfr/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.management.jfr/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.management.jfr/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.management/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.management/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.management/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.naming.dns/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.naming.dns/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.naming.dns/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.naming.rmi/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.naming.rmi/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.naming.rmi/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.net/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.net/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.net/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.nio.mapmode/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.nio.mapmode/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.nio.mapmode/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.random/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.random/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.random/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.sctp/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.sctp/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.sctp/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.security.auth/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.security.auth/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.security.auth/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.security.jgss/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.security.jgss/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.security.jgss/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.unsupported.desktop/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.unsupported.desktop/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.unsupported.desktop/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.unsupported/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.unsupported/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.unsupported/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.xml.dom/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.xml.dom/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.xml.dom/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.zipfs/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.zipfs/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-21.0.5-internal/legal/jdk.zipfs/LICENSE
/usr/lib/jvm/openjdk-21.0.5-internal/lib/classlist
/usr/lib/jvm/openjdk-21.0.5-internal/lib/ct.sym
/usr/lib/jvm/openjdk-21.0.5-internal/lib/jexec
/usr/lib/jvm/openjdk-21.0.5-internal/lib/jexec.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/lib/jfr/default.jfc
/usr/lib/jvm/openjdk-21.0.5-internal/lib/jfr/profile.jfc
/usr/lib/jvm/openjdk-21.0.5-internal/lib/jrt-fs.jar
/usr/lib/jvm/openjdk-21.0.5-internal/lib/jspawnhelper
/usr/lib/jvm/openjdk-21.0.5-internal/lib/jspawnhelper.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/lib/jvm.cfg
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libattach.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libawt.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libawt_headless.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libawt_xawt.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libdt_socket.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libextnet.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libfontmanager.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libinstrument.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libj2gss.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libj2pcsc.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libj2pkcs11.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libjaas.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libjava.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libjavajpeg.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libjawt.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libjdwp.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libjimage.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libjli.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libjsig.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libjsound.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libjsvml.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/lib/liblcms.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/lib/lible.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libmanagement.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libmanagement_agent.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libmanagement_ext.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libmlib_image.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libnet.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libnio.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libprefs.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/lib/librmi.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libsaproc.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libsctp.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libsplashscreen.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libsyslookup.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libverify.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libzip.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/lib/modules
/usr/lib/jvm/openjdk-21.0.5-internal/lib/psfont.properties.ja
/usr/lib/jvm/openjdk-21.0.5-internal/lib/psfontj2d.properties
/usr/lib/jvm/openjdk-21.0.5-internal/lib/security/blocked.certs
/usr/lib/jvm/openjdk-21.0.5-internal/lib/security/cacerts
/usr/lib/jvm/openjdk-21.0.5-internal/lib/security/default.policy
/usr/lib/jvm/openjdk-21.0.5-internal/lib/security/public_suffix_list.dat
/usr/lib/jvm/openjdk-21.0.5-internal/lib/server/classes.jsa
/usr/lib/jvm/openjdk-21.0.5-internal/lib/server/classes_nocoops.jsa
/usr/lib/jvm/openjdk-21.0.5-internal/lib/server/libjvm.debuginfo
/usr/lib/jvm/openjdk-21.0.5-internal/lib/src.zip
/usr/lib/jvm/openjdk-21.0.5-internal/lib/tzdb.dat
/usr/lib/jvm/openjdk-21.0.5-internal/man/man1/jar.1
/usr/lib/jvm/openjdk-21.0.5-internal/man/man1/jarsigner.1
/usr/lib/jvm/openjdk-21.0.5-internal/man/man1/java.1
/usr/lib/jvm/openjdk-21.0.5-internal/man/man1/javac.1
/usr/lib/jvm/openjdk-21.0.5-internal/man/man1/javadoc.1
/usr/lib/jvm/openjdk-21.0.5-internal/man/man1/javap.1
/usr/lib/jvm/openjdk-21.0.5-internal/man/man1/jcmd.1
/usr/lib/jvm/openjdk-21.0.5-internal/man/man1/jconsole.1
/usr/lib/jvm/openjdk-21.0.5-internal/man/man1/jdb.1
/usr/lib/jvm/openjdk-21.0.5-internal/man/man1/jdeprscan.1
/usr/lib/jvm/openjdk-21.0.5-internal/man/man1/jdeps.1
/usr/lib/jvm/openjdk-21.0.5-internal/man/man1/jfr.1
/usr/lib/jvm/openjdk-21.0.5-internal/man/man1/jhsdb.1
/usr/lib/jvm/openjdk-21.0.5-internal/man/man1/jinfo.1
/usr/lib/jvm/openjdk-21.0.5-internal/man/man1/jlink.1
/usr/lib/jvm/openjdk-21.0.5-internal/man/man1/jmap.1
/usr/lib/jvm/openjdk-21.0.5-internal/man/man1/jmod.1
/usr/lib/jvm/openjdk-21.0.5-internal/man/man1/jpackage.1
/usr/lib/jvm/openjdk-21.0.5-internal/man/man1/jps.1
/usr/lib/jvm/openjdk-21.0.5-internal/man/man1/jrunscript.1
/usr/lib/jvm/openjdk-21.0.5-internal/man/man1/jshell.1
/usr/lib/jvm/openjdk-21.0.5-internal/man/man1/jstack.1
/usr/lib/jvm/openjdk-21.0.5-internal/man/man1/jstat.1
/usr/lib/jvm/openjdk-21.0.5-internal/man/man1/jstatd.1
/usr/lib/jvm/openjdk-21.0.5-internal/man/man1/jwebserver.1
/usr/lib/jvm/openjdk-21.0.5-internal/man/man1/keytool.1
/usr/lib/jvm/openjdk-21.0.5-internal/man/man1/rmiregistry.1
/usr/lib/jvm/openjdk-21.0.5-internal/man/man1/serialver.1
/usr/lib/jvm/openjdk-21.0.5-internal/release

%files bin
%defattr(-,root,root,-)
/usr/bin/jar
/usr/bin/jar.debuginfo
/usr/bin/jarsigner
/usr/bin/jarsigner.debuginfo
/usr/bin/java
/usr/bin/java.debuginfo
/usr/bin/javac
/usr/bin/javac.debuginfo
/usr/bin/javadoc
/usr/bin/javadoc.debuginfo
/usr/bin/javap
/usr/bin/javap.debuginfo
/usr/bin/jcmd
/usr/bin/jcmd.debuginfo
/usr/bin/jconsole
/usr/bin/jconsole.debuginfo
/usr/bin/jdb
/usr/bin/jdb.debuginfo
/usr/bin/jdeprscan
/usr/bin/jdeprscan.debuginfo
/usr/bin/jdeps
/usr/bin/jdeps.debuginfo
/usr/bin/jfr
/usr/bin/jfr.debuginfo
/usr/bin/jhsdb
/usr/bin/jhsdb.debuginfo
/usr/bin/jimage
/usr/bin/jimage.debuginfo
/usr/bin/jinfo
/usr/bin/jinfo.debuginfo
/usr/bin/jlink
/usr/bin/jlink.debuginfo
/usr/bin/jmap
/usr/bin/jmap.debuginfo
/usr/bin/jmod
/usr/bin/jmod.debuginfo
/usr/bin/jpackage
/usr/bin/jpackage.debuginfo
/usr/bin/jps
/usr/bin/jps.debuginfo
/usr/bin/jrunscript
/usr/bin/jrunscript.debuginfo
/usr/bin/jshell
/usr/bin/jshell.debuginfo
/usr/bin/jstack
/usr/bin/jstack.debuginfo
/usr/bin/jstat
/usr/bin/jstat.debuginfo
/usr/bin/jstatd
/usr/bin/jstatd.debuginfo
/usr/bin/jwebserver
/usr/bin/jwebserver.debuginfo
/usr/bin/keytool
/usr/bin/keytool.debuginfo
/usr/bin/rmiregistry
/usr/bin/rmiregistry.debuginfo
/usr/bin/serialver
/usr/bin/serialver.debuginfo

%files dev
%defattr(-,root,root,-)
/usr/lib/jvm/openjdk-21.0.5-internal/include/classfile_constants.h
/usr/lib/jvm/openjdk-21.0.5-internal/include/jawt.h
/usr/lib/jvm/openjdk-21.0.5-internal/include/jdwpTransport.h
/usr/lib/jvm/openjdk-21.0.5-internal/include/jni.h
/usr/lib/jvm/openjdk-21.0.5-internal/include/jvmti.h
/usr/lib/jvm/openjdk-21.0.5-internal/include/jvmticmlr.h
/usr/lib/jvm/openjdk-21.0.5-internal/include/linux/jawt_md.h
/usr/lib/jvm/openjdk-21.0.5-internal/include/linux/jni_md.h

%files lib
%defattr(-,root,root,-)
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libattach.so
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libawt.so
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libawt_headless.so
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libawt_xawt.so
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libdt_socket.so
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libextnet.so
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libfontmanager.so
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libinstrument.so
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libj2gss.so
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libj2pcsc.so
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libj2pkcs11.so
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libjaas.so
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libjava.so
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libjavajpeg.so
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libjawt.so
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libjdwp.so
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libjimage.so
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libjli.so
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libjsig.so
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libjsound.so
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libjsvml.so
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/liblcms.so
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/lible.so
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libmanagement.so
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libmanagement_agent.so
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libmanagement_ext.so
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libmlib_image.so
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libnet.so
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libnio.so
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libprefs.so
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/librmi.so
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libsaproc.so
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libsctp.so
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libsplashscreen.so
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libsyslookup.so
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libverify.so
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/libzip.so
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/server/libjsig.so
/V3/usr/lib/jvm/openjdk-21.0.5-internal/lib/server/libjvm.so
/V3/usr/lib64/libjli.so
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libattach.so
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libawt.so
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libawt_headless.so
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libawt_xawt.so
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libdt_socket.so
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libextnet.so
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libfontmanager.so
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libinstrument.so
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libj2gss.so
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libj2pcsc.so
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libj2pkcs11.so
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libjaas.so
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libjava.so
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libjavajpeg.so
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libjawt.so
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libjdwp.so
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libjimage.so
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libjli.so
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libjsig.so
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libjsound.so
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libjsvml.so
/usr/lib/jvm/openjdk-21.0.5-internal/lib/liblcms.so
/usr/lib/jvm/openjdk-21.0.5-internal/lib/lible.so
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libmanagement.so
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libmanagement_agent.so
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libmanagement_ext.so
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libmlib_image.so
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libnet.so
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libnio.so
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libprefs.so
/usr/lib/jvm/openjdk-21.0.5-internal/lib/librmi.so
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libsaproc.so
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libsctp.so
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libsplashscreen.so
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libsyslookup.so
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libverify.so
/usr/lib/jvm/openjdk-21.0.5-internal/lib/libzip.so
/usr/lib/jvm/openjdk-21.0.5-internal/lib/server/libjsig.so
/usr/lib/jvm/openjdk-21.0.5-internal/lib/server/libjvm.so
/usr/lib64/libjli.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/openjdk/570f5344ea5facacb5e0bbb3fe4e0674189a5f0e
/usr/share/package-licenses/openjdk/a4fb972c240d89131ee9e16b845cd302e0ecb05f
/usr/share/package-licenses/openjdk/f9c9a2d3495a0766b4cf20d4b90cfe714dab3dc1
